config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'sessions#new'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  
  resources :users
  resources :sessions
  resources :events
  resources :teams

  get '/search' => 'events#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :teams

end

app/models/event_team.rb
class EventTeam < ApplicationRecord
  belongs_to :team
  belongs_to :event
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_users
  has_many :users, through: :team_users
  # belongs_to :team_captain, class_name: "User", foreign_key: "user_id"
  # accepts_nested_attributes_for :team_captain
  has_many :event_teams
  has_many :events, through: :event_teams
end

app/models/team_user.rb
class TeamUser < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 
  has_many :team_users
  has_many :teams, through: :team_users

  validates :name, :email, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]


  def self.from_omniauth auth
    self.find_user auth
  end
  
  private

  def self.find_user auth
    if auth.provider == "google_oauth2"
      username = auth.extra.raw_info.name
    end
    where( provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.email    = "#{auth.uid}@app.com"
      user.username = username
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  def after_sign_in_path_for(resource)
    user_path(current_user) || request.env['omniauth.origin'] || stored_location_for(resource)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  include EventHelper

  def index
    @city = params[:select][:city]
    @response = self.api(@city).html_safe

  end

  def show
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

  #For google and eventbrite api
  def search

    redirect_to :results
  end

  def results
  #   long = [37.789527]
  #   lati = [-122.394276]
  #  @events = Event.all
  #  @hash = Gmaps4rails.build_markers(@events) do |event, marker|
  #    long.each do |i|
  #      marker.lat long[i]
  #      marker.lng lati[i]
  #    end
    #  marker.title user.title
  #  end
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2

    $code_for_cal = params[:code]

    login request.env["omniauth.auth"]


  end

  private

  def login auth_hash

    @user = User.from_omniauth(auth_hash)
    @user.access_token = request.env["omniauth.auth"].credentials.token
    @user.refresh_token = request.env["omniauth.auth"].credentials.request_token
    @user.save


    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "#{auth_hash.provider}") if is_navigational_format?
    else
      session["devise.#{auth_hash.provider}_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @user = current_user
  end

  #     #############not sure if this belongs here#########

  # def search
  #   redirect_to :results
  # end

  # def results
  # #   long = [37.789527]
  # #   lati = [-122.394276]
  # #  @events = Event.all
  # #  @hash = Gmaps4rails.build_markers(@events) do |event, marker|
  # #    long.each do |i|
  # #      marker.lat long[i]
  # #      marker.lng lati[i]
  # #    end
  #   #  marker.title user.title
  # #  end
  # end  

  # ##############end of not sure :) ###############


  def create

  user = User.from_omniauth(env["omniauth.auth"])
  user.access_token = request.env["omniauth.auth"].credentials.token
  user.refresh_token = request.env["omniauth.auth"].credentials.request_token
  user.save
  session[:user_id] = user.id
  p "BLAHLDKFJDSL:KFJDSLF:KJSDF:LKJSDFL:BSDFJKDSFHLKDSJFLFKDSJF"
  p request.env["omniauth.auth"]
  p "THIS IS THE END OF THE THING THAT WE ARE TRYAN PRITN"
  redirect_to "users#show"

  end

  def destroy
  session[:user_id] = nil
  redirect_to root_path
  end

end

app/controllers/teams_controller.rb
class TeamController < ApplicationController
  
  def index
    @team = Team.all
  end

  #For google and eventbrite api

  def new
    @team = Team.find_or_create_by(params[:id])
  end

end

app/controllers/user_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
#   def login
#     session[:user_id] = @user.id
#   end

#   def logout
#     session[:user_id] = nil
#     current_user = false
#   end

#   def logged_in?
#     current_user ? true : false
#   end

#   def current_user
#     @current_user ||= User.find(session[:user_id]) if session[:user_id]
#   end
end

app/helpers/event_helper.rb
module EventHelper

  def api(city)
    token = ENV['EB_TOKEN']
    url = "https://www.eventbriteapi.com/v3/events/search/?token=#{token}&location.address=#{city}&q=hackathon"
    returnjson = HTTParty.get(url)
    html = format_html(returnjson)
    code = format_url(html)

    return code

  end

  def format_url(data)
    "<div class='event-search'>" + data + "</div>"
  end

  def format_html(input)

    html = ""

    input["events"].each do |inp|
      eventname = inp['name']['text']
      eventlink = inp['url']
      description = inp['description']['text']
      start = inp['start']['local']
      endd = inp['end']['local']

      html += "<h5><a href="+ eventlink +">" + eventname + "</a>
      " + "   " + start + " - " + endd + "
      <form method='post' action='/events/show'>
      <button type='submit'>Join Team</button> 
      </form></h5>
      <p>"+ description + "</p><br>"
    end
    return html
  end 
end

app/views/events/index.html.erb
<%= link_to "Profile", user_path(current_user) %>

<%= link_to "Home", root_path(@session) %>


<h3> Upcoming Hackathons </h3>

<div class="event-content">
  
<%= @response %>
</div>

app/views/events/new.html.erb
<%= link_to "Profile", user_path(current_user) %>


<%= link_to "Home", root_path(@session) %>




<form action= "/search" method="get" style="display: block;"/>
  <select name="select[city]">
    <option value="" disabled selected>Select City</option>
    <option value="sanfrancisco">San Francisco</option>
    <option value="seattle">Seattle</option>
    <option value="austin">Austin</option>
    <option value="sandiego">San Diego</option>
    <option value="chicago">Chicago</option>
    <option value="newyork">New York</option>
  </select>
  <input type="Submit" value="Search" class="btn-large waves-effect waves-light teal lighten-1">
</form>

app/views/events/show.html.erb
<%= link_to "Profile", user_path(current_user) %>


<%= link_to "Home", root_path(@session) %>


<p> Event Details </p>

  <ul> 
    <li>name</li>
    <li>location</li>
    <li>description</li>
    <li>date</li>
    <li>reg_fee</li>
    <li>team</li>
  </ul>
        <%= link_to "Sign Up For Team", new_team_path(@team), class: "btn-large waves-effect waves-light teal lighten-1"%>

app/views/home/results.html.erb
<script src="//maps.google.com/maps/api/js?key="></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

  <div style='width: 800px;'>
    <div id="geolocation" style='width: 800px; height: 400px;'></div>
  </div>

<script type="text/javascript">
var handler = Gmaps.build('Google');
var markers = [
      ['London Eye, London', 51.503454,-0.119562],
      ['Palace of Westminster, London', 51.499633,-0.124755]
  ];
handler.buildMap({ internal: {id: 'geolocation'} }, function(){
  // for( i = 0; i < markers.length; i++ ) {
  //      var position = new google.maps.LatLng(markers[i][1], markers[i][2]);
  //      bounds.extend(position);
  //      markers = new google.maps.Marker({
  //          position: position,
  //          map: map,
  //          title: markers[i][0]
  //      });
  // be aware chrome >= 50 requires https for geolocation to work
  markers = handler.addMarkers([
  {
    "lat": 37.789527,
    "lng": -122.394276,
    "picture": {
      "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
      "width":  36,
      "height": 36
    },
    "infowindow": "Global AI Hackathon Fri, Jun 23, 2017, 7:00 PM – Sun, Jun 25, 2017, 6:00 PM PDT"
  },

  {
    "lat": 37.7859008,
    "lng":  -122.4108333,
    "picture": {
      "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
      "width":  36,
      "height": 36
    },
    "infowindow": "DocuSign Momentum Hackathon 2017 Tuesday, May 2, 2017 | Wednesday, May 3, 2017"
  },

  {
    "lat": 37.7836966,
    "lng":  -122.4089664,
    "picture": {
      "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
      "width":  36,
      "height": 36
    },
    "infowindow": "Blockchain Hackathon | Bitcoin for your Thoughts?Fri, Mar 24, 2017, 7:00 PM – Sun, Mar 26, 2017, 7:30 PM PDT "
  },

  {
    "lat": 37.7844452,
    "lng": -122.4049522,
    "picture": {
      "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
      "width":  36,
      "height": 36
    },
    "infowindow": "Ctrl Alt Delete Hate Hackathon Sat, Apr 1, 2017, 9:00 AM – Sun, Apr 2, 2017, 4:00 PM PDT"

  },



]);
  if(navigator.geolocation)
    navigator.geolocation.getCurrentPosition(displayOnMap);

});

function displayOnMap(position){
  var marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude
  });
  handler.map.centerOn(marker);
};

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Squad</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <script src="//maps.google.com/maps/api/js?key="></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

</head>

<body>
  <%= yield %>
</body>
</html>

app/views/users/show.html.erb
<h1>Hello, <%=@user.username %></h1>  
<%= link_to "Search", new_event_path(@events) %>
<p>Your Upcoming Events</p>

<ul>
    <li>
        Nasa Hackathon
        <ul>
            <li>Tony @email</li>
            <li>Shean @email</li>
            <li>Bob @email</li>
        </ul>
    </li>
    <br>
    <li>
        DBC Hackathon
        <ul>
            <li>Mark @email</li>
            <li>Brian @email</li>
            <li>Greg @email</li>
        </ul>
    </li>
    <br>
    <li>
        Pickles Hackathon
        <ul>
            <li>Peter @email</li>
            <li>Susan @email</li>
            <li>Sara @email</li>
        </ul>
    </li>        
</ul>
<br>
<p>---------------------------------------------------------------
------------------------------------------------------------------
------------------------------------------------------------------</p>
<p> Past Hackathons</p>

<ul>
    <li>
        Some Hackathon
        <ul>
            <li>Tony @email</li>
            <li>Shean @email</li>
            <li>Bob @email</li>
        </ul>
    </li>
    <br>
    <li>
        Another Hackathon
        <ul>
            <li>Mark @email</li>
            <li>Brian @email</li>
            <li>Greg @email</li>
        </ul>
    </li>
    <br>
    <li>
        Third Random Hackathon
        <ul>
            <li>Peter @email</li>
            <li>Susan @email</li>
            <li>Sara @email</li>
        </ul>
    </li>        
</ul>
    
        <div class="col l3 s12">
          <br><br><br>

            <a href="/users/sign_out" data-method="delete" class="waves-effect waves-light btn-large">Logout</a>

        </div>